### ISSUE TITLE
Check failed in method <init> of class com.ruzzi.fullsparql.algebra.operator.Projection

### ISSUE THREAD

**Issue by roodsey** [obdasystems/monolith-releases#39]
No user error message

Content-URL: 
https://raw.githubusercontent.com/obdasystems/monolith-releases/main/reports/IssueReport_e4530d34-994e-451f-a6b0-f1f29b58ae67

**Comment by roodsey** [comment]
Provando le construct ho rilevato l'errore allegato in questo issue report.
Assegno a @NonnonePalmiro perché dalla traccia mi pare inerente a FS.
Per scaricare i dati per riprodurre l'errore, si può utilizzare la classe `IssueReportDownloader`, eseguibile a cui va passata la Content-URL presente nella issue e il percorso ad una cartella (che verrà creata, quindi non deve esistere) in cui verrà scaricata la specifica e la query). 
```java
java.lang.RuntimeException: Check failed in method <init> of class com.ruzzi.fullsparql.algebra.operator.Projection
	at it.uniroma1.dis.mastro.api.tools.GlobalTools.checkTrue(GlobalTools.java:162)
	at com.ruzzi.fullsparql.algebra.operator.Projection.<init>(Projection.java:32)
	at com.ruzzi.fullsparql.algebra.visitors.Sparql2MastroAlgebraOperatorVisitor.visit(Sparql2MastroAlgebraOperatorVisitor.java:446)
	at org.apache.jena.sparql.algebra.op.OpProject.visit(OpProject.java:47)
	at com.ruzzi.fullsparql.algebra.processor.Sparql2MastroAlgebraTranslator.translate(Sparql2MastroAlgebraTranslator.java:133)
	at com.ruzzi.fullsparql.algebra.processor.BasicSparql2SqlTranslator.noSubQueryTranslate(BasicSparql2SqlTranslator.java:111)
	at com.ruzzi.fullsparql.algebra.processor.BasicSparql2SqlTranslator.translate(BasicSparql2SqlTranslator.java:103)
	at com.ruzzi.fullsparql.FullSparqlStreamQueryThread.runQuery(FullSparqlStreamQueryThread.java:213)
	at com.ruzzi.fullsparql.FullSparqlStreamQueryThread.run(FullSparqlStreamQueryThread.java:329)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NonnonePalmiro** [comment]
Il problema era che non veniva rilanciata opportunamente una eccezione generata dalla classe SqlUnfolding per cui ho aperto la issue https://github.com/obdasystems/monolith-releases/issues/40
