### ISSUE TITLE
Errore SQLUnfolding

### ISSUE THREAD

**Issue by NonnonePalmiro** [obdasystems/monolith-releases#40]
Una volta corretto il bug https://github.com/obdasystems/monolith-releases/issues/39 , l'esecuzione della stessa query sulla stessa specifica riportata nell'altra issue, ritorna la seguente eccezione

```java
Check failed in method <init> of class com.ruzzi.fullsparql.SqlUnfolding
	at it.uniroma1.dis.mastro.api.tools.GlobalTools.checkTrue(GlobalTools.java:162)
	at com.ruzzi.fullsparql.SqlUnfolding.<init>(SqlUnfolding.java:50)
	at com.ruzzi.fullsparql.SqlUnfolding.generateSqlUnfolding(SqlUnfolding.java:187)
	at com.ruzzi.fullsparql.algebra.AlgebraUtils.processCoreQuery(AlgebraUtils.java:165)
	at com.ruzzi.fullsparql.algebra.AlgebraUtils.processCoreQuery(AlgebraUtils.java:147)
	at com.ruzzi.fullsparql.algebra.visitors.Sparql2MastroAlgebraOperatorVisitor.visit(Sparql2MastroAlgebraOperatorVisitor.java:216)
	at org.apache.jena.sparql.algebra.op.OpBGP.visit(OpBGP.java:49)
	at com.ruzzi.fullsparql.algebra.visitors.Sparql2MastroAlgebraOperatorVisitor.visit(Sparql2MastroAlgebraOperatorVisitor.java:463)
	at org.apache.jena.sparql.algebra.op.OpProject.visit(OpProject.java:47)
	at com.ruzzi.fullsparql.algebra.processor.Sparql2MastroAlgebraTranslator.translate(Sparql2MastroAlgebraTranslator.java:133)
	at com.ruzzi.fullsparql.algebra.processor.BasicSparql2SqlTranslator.noSubQueryTranslate(BasicSparql2SqlTranslator.java:111)
	at com.ruzzi.fullsparql.algebra.processor.BasicSparql2SqlTranslator.translate(BasicSparql2SqlTranslator.java:103)
	at com.ruzzi.fullsparql.algebra.TranslatorTest.runTestStructuralQuery(TranslatorTest.java:1758)
	at com.ruzzi.fullsparql.algebra.TranslatorTest.main(TranslatorTest.java:125)
```

**Comment by roodsey** [comment]
L'errore segnalato non si verifica con la specifica relativa alla #39.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/20337479/164641960-2712d831-c904-429a-b3f7-d2618d644ffa.png">
